
---
- name: "Update apt packages"
  become: true
  apt:
    update_cache: yes

- name: "Upgrade apt packages."
  become: true
  apt:
    upgrade: "yes"

- name: "Remove redundant dependencies"
  become: true
  apt:
    autoremove: yes

- name: "install node and npm."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2 - globally"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present